### ISSUE TITLE
Important Maintenance Considerations.

### ISSUE THREAD

**Issue by deepio** [hsnr-gamera/gamera#13]
@cdalitz @danstender 
The travis build should guarantee a working build, without any substitutions. A 'passing' travis build badge, in its current state, is misleading.
https://github.com/hsnr-gamera/gamera/blob/096270731e249256af7ba0fd7fdbf3980d630b49/.travis.yml#L9
- This installation does not include wx. If Gamera is to be maintained, again this is a suggestion, the dependencies should also be maintained. This includes moving incrementally from wxpython 2.8 to 3, and so on to the latest. As it stands, Gamera GUI can not be installed easily because of issues surrounding wx.
- A second option is to drop support for the mac GUI, and concentrate on properly maintaining a stable debian package only. Here wx could also be replaced with another project.
- The last option is to drop the GUI completely (and wx with it.)

https://wxpython.org/Phoenix/docs/html/MigrationGuide.html
https://docs.travis-ci.com/user/gui-and-headless-browsers/

**Comment by cdalitz** [comment]
Your question/suggestion does not privide much context what "travis" is, but if it is a Linux distribution without a GUI: it is already possible to install Gamera without wx:
`python setup.py --nowx build`
The mac GUI is required because I myself use Gamera on a OSX and there are detailed instructions how to install Gamera on OSX.
I agree that a port to wxpython "Phoenix" is desirable, but it is also considerable effort. It will become obligatory when wxpython 3.x can no longer be isntalled on newer distributions.

**Comment by cdalitz** [comment]
Recently, I have installed Gamera on OSX High Sierra, which is quite cumbersome due to Apple's "system integrity protection", which prevents third party python modules to be installed into the python that comes with the OS. I have described the necessary steps  here:
[](http://gamera.informatik.hsnr.de/docs/gamera-docs/install.html#installation-on-10-11-el-captain-and-above)
Do these instructions work for you? If not: what did not work?

**Comment by deepio** [comment]
```
#include <QuickTime/QuickTime.h>

[0;1;32m         ^~~~~~~~~~~~~~~~~~~~~~~

[0m10 warnings and 1 error generated.

make: *** [monodll_core_bitmap.o] Error 1

make: *** Waiting for unfinished jobs....

10 warnings generated.

Error building

ERROR: failed building wxWidgets

Traceback (most recent call last):

  File "build-wxpython.py", line 389, in <module>

    wxbuild.main(wxscript, build_options)

  File "/Users/travis/build/deepio/gamera/wxPython-src-3.0.2.0/build/tools/build-wxwidgets.py", line 485, in main

    exitIfError(wxBuilder.build(dir=buildDir, options=args), "Error building")

  File "/Users/travis/build/deepio/gamera/wxPython-src-3.0.2.0/build/tools/build-wxwidgets.py", line 80, in exitIfError

    raise builder.BuildError(msg)

BuildError
```

**Comment by deepio** [comment]
UBUNTU-14.04
OSX-10.13 (xcode9.4)
OSX-10.13 (xcode9.3)
OSX-10.12 (xcode9.2)
OSX-10.12 (xcode9.1)
OSX-10.12 (xcode9)
OSX-10.12 (xcode8.3.3)
OSX-10.11 (xcode8gm)
https://travis-ci.com/deepio/gamera

They all have different errors. Whereas, I can install gamera gui with apt-get on ubuntu 18.04.
